### ISSUE TITLE
173022-Please check IGST amount showing is not correct in PO Printout due to Back order qty increase.

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#523]
173022-Please check IGST amount showing is not correct in PO Printout due to Back order qty increase.

**Comment by ravik200** [comment]
[Test Document for Please check IGST amount showing is not correct in PO Printout due to Back order qty increase.docx](https://github.com/Isgec/ERPLN/files/6153893/Test.Document.for.Please.check.IGST.amount.showing.is.not.correct.in.PO.Printout.due.to.Back.order.qty.increase.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test.

**Comment by Pankaj9583** [comment]
Testing done and its working fine.
[173022-Please check IGST amount showing is not correct in PO Printout due to Back order qty increase._523.docx](https://github.com/Isgec/ERPLN/files/6168617/173022-Please.check.IGST.amount.showing.is.not.correct.in.PO.Printout.due.to.Back.order.qty.increase._523.docx)

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
